variable "function_name" {}
variable "container_registry" {}
variable "container_repository" {}
variable "container_image_tag" {}
variable "ram_mib" {}
variable "timeout_s" {}
variable "eks_cluster_name" {}
variable "attach_eks_policy" {}
variable "attach_cloudwatch_policy" {}
variable "attach_lambda_policy" {}
variable "region" {}
variable "db_api_url" {}
variable "route53_domain" {}
variable "environment" {}
variable "random_string" {}